# Generated by Django 2.0.4 on 2018-04-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('course_rating', models.PositiveSmallIntegerField(validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(5)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golfer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveSmallIntegerField(null=True, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(18)])),
                ('par_type', models.PositiveSmallIntegerField(null=True, validators=[rest_framework.compat.MinValueValidator(3), rest_framework.compat.MaxValueValidator(5)])),
                ('hole_length', models.PositiveSmallIntegerField(null=True)),
                ('player_score', models.PositiveSmallIntegerField(null=True, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(12)])),
                ('green_in_regulation', models.BooleanField(default=False)),
                ('fairway_in_regulation', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hole_number'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_total', models.PositiveSmallIntegerField(null=True, validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(75)])),
                ('course_name', models.CharField(max_length=131)),
                ('course_length', models.PositiveSmallIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_app.Golfer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='hole',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Scorecard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.Golfer'),
        ),
    ]
