# Generated by Django 2.0.4 on 2018-04-28 01:18

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='putts',
            field=models.PositiveSmallIntegerField(null=True, validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(20)]),
        ),
    ]
